events {
    worker_connections 1024;
}

http {
    # Definición de la granja de servidores (Upstream Load Balancer)
    upstream devops_backend_nodes {
        server devops-app-1:8080;
        server devops-app-2:8080;
    }

    server {
        listen 80;
        server_name localhost;

        # Configuración del Endpoint unificado exigido en el reto
        location /DevOps {
            proxy_pass http://devops_backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Tiempos de respuesta para evitar timeouts durante la carga
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }

        # Manejo de cualquier otra ruta que no sea /DevOps
        location / {
            return 404 "Not Found - Use /DevOps endpoint with POST method";
        }
    }
}