apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
  namespace: devops-app
data:
  SERVER_PORT: "8080"
  LOGGING_LEVEL_COM_ANAX_DEVOPS: "DEBUG"
   # Valores codificados en Base64 para el almacenamiento seguro en la API de K8s
  API_KEY: MmY1YWU5NmMtYjU1OC00YzdiLWE1OTAtYTUwMWFlMWMzZjZj # API_KEY=2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
  JWT_SECRET: bnR0LWRhdGEtZGV2b3BzLXBsYXRmb3JtLWNoYWxsZW5nZS1zdXBlci1zZWNyZXQta2V5LTIwMjY=