name: "Continuous Deployment to AWS Production"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  infrastructure-and-delivery:
    name: "Terraform Apply & K8s Continuous Delivery"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Initialization & Apply
        run: |
          cd terraform/environments/prod
          terraform init
          terraform apply -auto-approve

      - name: Capture EC2 Live Public IP
        id: get_ip
        run: |
          cd terraform/environments/prod
          IP=$(terraform output -raw k3s_server_ip)
          echo "server_ip=$IP" >> $GITHUB_OUTPUT

      - name: Configure SSH Key and Connect to K3s Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get_ip.outputs.server_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

          script: |
            # 1. Instalar Kong Ingress Controller
            sudo kubectl apply -f https://bit.ly/k8s-kong-2.12

            # 2. Clonar repositorio
            rm -rf devops-platform-challenge
            git clone https://github.com/${{ github.repository }}.git

            cd devops-platform-challenge/k8s/base

            # 3. Reemplazar tag dinámicamente
            sed -i "s|image: andy17u7/devops-challenge:latest|image: andy17u7/devops-challenge:${{ github.sha }}|g" deployment.yaml

            # 4. Deploy con Kustomize
            sudo kubectl apply -k .

            # 5. Monitoring stack
            if [ -f ../monitoring.yaml ]; then
              sudo kubectl apply -f ../monitoring.yaml
            fi

            # 6. Verificar rollout
            sudo kubectl rollout status deployment/devops-service -n devops-app

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Testing Dependencies
        run: |
          pip install requests python-dotenv

      - name: Execute Automated Smoke Test (E2E Verification)
        env:
          APP_HOST: ${{ steps.get_ip.outputs.server_ip }}
          APP_PORT: "80"
          API_KEY: ${{ secrets.TEST_API_KEY }}

        run: |
          chmod +x ./test_endpoint.py
          python ./test_endpoint.py