name: "Main Orchestrator Reto DevOps Platform"

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'instalations/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ "main", "dev" ]
    # También aplicar filtros en PR para ser consistentes
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'instalations/**'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch: # Permite ejecuciones bajo demanda exigidas en el reto

jobs:
  # Ejecuta CI siempre
  Job-CI:
    uses: ./.github/workflows/ci.yml

  # Ejecuta Docker solo si CI termina bien
  Job-Docker:
    needs: Job-CI
    uses: ./.github/workflows/docker.yml

  # Ejecuta CD solo si es la rama MAIN, hubo PUSH (o merge) y Docker terminó bien
  Job-CD:
    needs: Job-Docker
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/cd.yml